[package]
name = "bincol"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = { version = "2.12.1", features = ["serde"] }
itertools = "0.14.0"
nonmax = { version = "0.5.5", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
smallvec = "1.15.1"
thiserror = "2.0.17"

[dev-dependencies]
ron = "0.12.0"
serde_json = "1.0.146"

[[example]]
name = "check"
